// Icon set — Phosphor (@phosphor-icons/react), re-exported under the names the app
// already uses so call sites and `className` sizing stay unchanged. Swap the icon
// for a name here in one place. Runtime icons come from the SSR (context-free) entry;
// the `Icon` type comes from the package root (type-only, erased at build).

export {
  // same name in both sets
  ArrowRight,
  ArrowUp,
  Check,
  Clock,
  Database,
  Eye,
  FileText,
  GitBranch,
  ListChecks,
  MapPin,
  Megaphone,
  PauseCircle,
  Pencil,
  Phone,
  PhoneCall,
  Play,
  PlayCircle,
  Plus,
  SlidersHorizontal,
  Tag,
  Target,
  Upload,
  CalendarCheck,
  Bell,
  Briefcase,
  Cpu,
  Crosshair,
  Gauge,
  Globe,
  Info,
  Square,
  Sun,
  UserPlus,
  Users,
  X,
  // renamed lucide → phosphor
  Buildings as Building2,
  WarningCircle as AlertCircle,
  CalendarDots as CalendarClock,
  CalendarBlank as CalendarDays,
  CurrencyCircleDollar as CircleDollarSign,
  RadioButton as CircleDot,
  Funnel as Filter,
  CircleNotch as Loader2,
  NotePencil as MessageSquarePlus,
  ArrowsClockwise as RefreshCw,
  TrendUp as TrendingUp,
  CheckCircle as CheckCircle2,
  CaretDown as ChevronDown,
  CaretRight as ChevronRight,
  CaretUp as ChevronUp,
  ArrowSquareOut as ExternalLink,
  House as Home,
  Stack as Layers,
  SquaresFour as LayoutGrid,
  Link as Link2,
  Envelope as Mail,
  ChatCircle as MessageCircle,
  Chat as MessageSquare,
  ChatDots as MessageSquareDashed,
  ChatText as MessageSquareText,
  Chats as MessagesSquare,
  ArrowBendUpLeft as Reply,
  ArrowBendUpLeft as MessageSquareReply,
  ArrowCounterClockwise as RotateCcw,
  FloppyDisk as Save,
  MagnifyingGlass as Search,
  Microphone as Mic,
  PaperPlaneTilt as Send,
  Gear as Settings,
  SignOut as LogOut,
  Sparkle as Sparkles,
  Trash as Trash2,
  MagicWand as Wand2,
  Lightning as Zap,
  Pulse as Activity,
} from "@phosphor-icons/react/dist/ssr";

// The icon component type (kept under the old name so existing annotations work).
export type { Icon as LucideIcon } from "@phosphor-icons/react";
